---
title: "Growth Curve Report"
author: "Randy L Coryell"
date: "June 22, 2016"
output: pdf_document
toc: true
toc_depth: 4
---


## Overview of Growth Study

This report will highlight data aquired during a 8h growth study to "investigate the neutrality of *Tn7* antibiotic (CAM) neutral marker insertion in *Vibrio fischeri* 

>###Strains:

>>>>ES114

>>>>ET401

>>>>EM17

>>*Note* All cultures were derived from a single colony, isolated on CAM plates (2.5ug/mL) and grown in liquid SWT (100mL) overnight. These overnight cultures were used to innoculate fresh SWT (100mL) media and grown at 225rpm and 28C for 1.5h. After taking a turbity measurement via spectrophotometry, each strain was diluted by placing a volume of this 1.5h culture into 100ml of fresh SWT. An initial OD was taken and the cultures were then placed into a shaking incubator @ 28C and 225RPM for the study.


***
> I want to walk down the street and have people say 'There goes Roy Hobbs, the best to ever play the game'.

>> Robert Redford, The Natural

***


## Installation of R packages 
Certain R packages, available on the CRAN repository, are required for this analysis.

```{undefinedecho=FALSE}
install.packages(c('reshape2', 'dplyr', 'ggplot2'))

```
